service: circleci-build-trigger

provider:
  name: aws
  runtime: nodejs4.3
  region: ${env:AWS_DEFAULT_REGION, env:AWS_REGION}

custom:
  writeEnvVars: ${file(serverless.env.yml)}

functions:
  trigger:
    handler: handler.trigger
    description: ${self:custom.writeEnvVars.PROJECT}
    events:
      - schedule: ${self:custom.writeEnvVars.SCHEDULE_EXPRESSION}

plugins:
  - serverless-plugin-write-env-vars
