service: circleci-build-trigger

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-northeast-1

functions:
  trigger:
    handler: handler.trigger
    events:
      - schedule: ${env:SCHEDULE_EXPRESSION}
